## Numpy - Broadcasting

Broadcasting es una serie de normas para aplicar funciones universales (añadir, eliminar, multiplicar, etc.) en arrays de distintos tamaños

Para arrays del mismo tamaño, las operaciones se realizan bajo una regla de elemento por elemento dentro del array


In [1]:
import numpy as np

In [2]:
x = np.arange(10)
y = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x + y

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

A través del broadcasting, podemos realizar operaciones del mismo tipo que la anterior sobre arrays que tienen tamaños distintos

In [6]:
a = np.ones((3,3))

In [7]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
a + x

ValueError: operands could not be broadcast together with shapes (3,3) (10,) 

In [9]:
z = np.arange(3)

Al sumar a + z, lo que hace virtualmente Python es completar el array z con dos filas
más idénticas y entonces suma los valores

In [12]:
a + z

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

Se puede hacer también en vertical

In [15]:
g = np.ones((3,1))

In [16]:
g

array([[1.],
       [1.],
       [1.]])

In [18]:
h = np.full((3,2), 2)

In [19]:
h

array([[2, 2],
       [2, 2],
       [2, 2]])

In [20]:
g + h

array([[3., 3.],
       [3., 3.],
       [3., 3.]])

In [23]:
h = np.full((1,3), 2)

In [25]:
h

array([[2, 2, 2]])

In [24]:
g + h

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [28]:
j = np.array(([1],
             [2],
             [3],
             [4],
             [5]))

In [30]:
k = np.array(([6,7]))

In [31]:
j + k

array([[ 7,  8],
       [ 8,  9],
       [ 9, 10],
       [10, 11],
       [11, 12]])

In [32]:
M = np.ones((2,3))
a = np.arange(3)

In [36]:
M.shape

(2, 3)

In [37]:
a.shape

(3,)

In [57]:
M.ndim

2

In [58]:
a.ndim

1

In [44]:
a + M

array([[1., 2., 3.],
       [1., 2., 3.]])

In [46]:
np.arange(10).shape

(10,)

In [53]:
o = np.ones((4,1))

In [54]:
o

array([[1.],
       [1.],
       [1.],
       [1.]])

In [55]:
o.ndim

2

In [56]:
a.ndim

1

In [2]:
h = np.ones((3,2))
i = np.array([1])

In [3]:
h

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [4]:
i

array([1])

In [5]:
h.shape

(3, 2)

In [6]:
i.shape

(1,)

In [7]:
h+i

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [8]:
j= np.arange(3)

In [9]:
j

array([0, 1, 2])

In [10]:
j.shape

(3,)

In [11]:
h+j

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 