## Numpy - Basic Indexing and Slicing

In [18]:
import numpy as np

### 2 dimensiones

In [5]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr2d[2]

array([7, 8, 9])

In [9]:
arr2d[0] =  11

In [10]:
arr2d


array([[11, 11, 11],
       [ 4,  5,  6],
       [ 7,  8,  9]])

### 3 dimensiones

In [11]:
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                  [[11,12,13],[14,15,16],[17,18,19]]])

In [12]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [14]:
arr3d.ndim

3

In [15]:
arr3d.shape


(2, 3, 3)

In [21]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr3d[0,1]

array([4, 5, 6])

## Boolean Indexing

Se pueden realizar subselecciones en el array, utilizando como filtros, arrays booleanos.

Selecciona aquellos en los que el valor es True.

!! Atención, siempre que se hace una subselección por valores
booleanos, SE CREA UNA COPIA del array,  incluso si el array
devuelto es igual que el original !!


In [20]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [22]:
data= np.random.randn(7,4)

In [23]:
data

array([[ 0.94122869,  0.07644921, -0.1658253 ,  0.08138635],
       [ 0.93378953,  2.0832738 , -1.2881831 , -0.65616999],
       [ 0.36483382, -1.30008441, -1.02978869,  0.26768644],
       [-0.73140415, -1.01661321, -0.20670884, -0.20453093],
       [ 0.5919085 , -1.49374556,  0.39171511, -1.13855594],
       [ 1.26453749,  0.34262221, -1.83157577, -0.91918584],
       [-0.1758048 ,  0.91922289,  1.42688314, -0.03098133]])

In [27]:
names == 'Bob' # devuelve un array booleano

array([ True, False, False,  True, False, False, False])

In [28]:
data[names == 'Bob'] # selecciona aquellas filas que son True

array([[ 0.94122869,  0.07644921, -0.1658253 ,  0.08138635],
       [-0.73140415, -1.01661321, -0.20670884, -0.20453093]])

In [30]:
data[names == 'Bob', :2] # de las filas seleccionadas, filtra columnas

array([[ 0.94122869,  0.07644921],
       [-0.73140415, -1.01661321]])

In [31]:
names2 = np.array(['Bob', 'Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [33]:
data[names2 == 'Bob'] 
# el array booleano tiene que ser del mismo tamaño del indice
# que estamos tratando

IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 8

In [34]:
data[~(names == 'Bob')] #selecciona aquello distinto a la selección

array([[ 0.93378953,  2.0832738 , -1.2881831 , -0.65616999],
       [ 0.36483382, -1.30008441, -1.02978869,  0.26768644],
       [ 0.5919085 , -1.49374556,  0.39171511, -1.13855594],
       [ 1.26453749,  0.34262221, -1.83157577, -0.91918584],
       [-0.1758048 ,  0.91922289,  1.42688314, -0.03098133]])

El operador  ~ puede ser útil cuando quieres invertir una condición

In [39]:
data[(names == 'Bob') | (names == 'Will')] 
# selecciona aquellas filas que son True anidando condiciones

array([[ 0.94122869,  0.07644921, -0.1658253 ,  0.08138635],
       [ 0.36483382, -1.30008441, -1.02978869,  0.26768644],
       [-0.73140415, -1.01661321, -0.20670884, -0.20453093],
       [ 0.5919085 , -1.49374556,  0.39171511, -1.13855594]])

In [40]:
data2 = data[(names == 'Bob') | (names == 'Will')]

In [41]:
data2

array([[ 0.94122869,  0.07644921, -0.1658253 ,  0.08138635],
       [ 0.36483382, -1.30008441, -1.02978869,  0.26768644],
       [-0.73140415, -1.01661321, -0.20670884, -0.20453093],
       [ 0.5919085 , -1.49374556,  0.39171511, -1.13855594]])

Si seleccionamos en el array con valores booleanos, se crea una copia,
si modificamos el valor, no afectamos al original

In [43]:
data2[0,0] = 0.3

In [44]:
data2

array([[ 0.3       ,  0.07644921, -0.1658253 ,  0.08138635],
       [ 0.36483382, -1.30008441, -1.02978869,  0.26768644],
       [-0.73140415, -1.01661321, -0.20670884, -0.20453093],
       [ 0.5919085 , -1.49374556,  0.39171511, -1.13855594]])

In [45]:
data

array([[ 0.94122869,  0.07644921, -0.1658253 ,  0.08138635],
       [ 0.93378953,  2.0832738 , -1.2881831 , -0.65616999],
       [ 0.36483382, -1.30008441, -1.02978869,  0.26768644],
       [-0.73140415, -1.01661321, -0.20670884, -0.20453093],
       [ 0.5919085 , -1.49374556,  0.39171511, -1.13855594],
       [ 1.26453749,  0.34262221, -1.83157577, -0.91918584],
       [-0.1758048 ,  0.91922289,  1.42688314, -0.03098133]])

Si creamos un indice a través de Slicing, se crea una vista
del array original

In [71]:
data4 = data[0,:]

In [72]:
type(data4)

numpy.ndarray

In [67]:
data4

array([ 0.94122869,  0.07644921, -0.1658253 ,  0.08138635])

Modicamos los datos del array con la subselección

In [73]:
data4[:] = 3

In [74]:
type(data4)

numpy.ndarray

In [75]:
data4

array([3., 3., 3., 3.])

Los cambios en la subselección, modifican los valores del
array original

In [76]:
data

array([[ 3.        ,  3.        ,  3.        ,  3.        ],
       [ 0.93378953,  2.0832738 , -1.2881831 , -0.65616999],
       [ 0.36483382, -1.30008441, -1.02978869,  0.26768644],
       [-0.73140415, -1.01661321, -0.20670884, -0.20453093],
       [ 0.5919085 , -1.49374556,  0.39171511, -1.13855594],
       [ 1.26453749,  0.34262221, -1.83157577, -0.91918584],
       [-0.1758048 ,  0.91922289,  1.42688314, -0.03098133]])

No igualar los datos de la subselección a capón porque cambias
la variable

In [77]:
data4 = 1

Pasa a ser una variable de tipo int

In [78]:
 type(data4)

int

In [79]:
data

array([[ 3.        ,  3.        ,  3.        ,  3.        ],
       [ 0.93378953,  2.0832738 , -1.2881831 , -0.65616999],
       [ 0.36483382, -1.30008441, -1.02978869,  0.26768644],
       [-0.73140415, -1.01661321, -0.20670884, -0.20453093],
       [ 0.5919085 , -1.49374556,  0.39171511, -1.13855594],
       [ 1.26453749,  0.34262221, -1.83157577, -0.91918584],
       [-0.1758048 ,  0.91922289,  1.42688314, -0.03098133]])

Podemos asignar valores en base a la subselección

In [80]:
data[data < 0] = 0

In [81]:
data

array([[3.        , 3.        , 3.        , 3.        ],
       [0.93378953, 2.0832738 , 0.        , 0.        ],
       [0.36483382, 0.        , 0.        , 0.26768644],
       [0.        , 0.        , 0.        , 0.        ],
       [0.5919085 , 0.        , 0.39171511, 0.        ],
       [1.26453749, 0.34262221, 0.        , 0.        ],
       [0.        , 0.91922289, 1.42688314, 0.        ]])


## Transposing Arrays

In [82]:
arr = np.arange(15).reshape((3,5))

In [83]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [84]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

## Multiplicación de matrices

Dos matrices se pueden multiplicar si el número de columnas de la
matriz A es igual al número de filas de la matriz B


        a11 a12 a13
 A      a21 a22 a23
        a31 a32 a33

Shape (3,3)

        b11 b12 b13
 B      b21 b22 b23
        b31 b32 b33

Shape (3,3)


A * B 

Se multiplica la fila por la columna en cada uno de sus 
valores y el resultado es el correspondiente de la celda

Ejemplo

Celda11 = a11 * b11 + a12 * b21 + a13 * b3


In [86]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [87]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

 #### Matriz transpuesta por su matriz
 
 Matriz A: 5 x 3 
 Matriz B: 3 x 5
 
 Matriz resultante: 5 x 5
 
 
 

In [85]:
np.dot (arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

Celda11 = 0 x 0 + 5 x 5 + 10 x 10 = 125
CeldaXX = Etc, etc

In [90]:
arr3 = np.arange(9).reshape((3,3))

In [91]:
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [92]:
arr4 = np.arange(9).reshape((3,3))

In [93]:
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
np.dot(arr3, arr4)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [96]:
np.sign(arr4) # determina el signo de cada elemento 1+ 0-

array([[0, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [97]:
np.ceil(arr4)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [98]:
data= np.random.randn(7,4)

In [100]:
data

array([[-1.97696942,  0.03951091,  0.72975879, -0.91479572],
       [ 1.11712003, -0.69278979, -0.16454356,  1.11890073],
       [-0.92112628,  1.49994811,  0.09167615, -0.17076331],
       [-1.02878243,  0.16361544,  0.62628984,  1.07207584],
       [-1.36968275, -1.18175284,  0.22646402, -0.87985383],
       [-1.0750434 , -0.79882925, -0.30056976,  0.92361285],
       [-0.08016755, -2.0701819 ,  0.75528139, -0.48997173]])

In [99]:
np.ceil(data)

array([[-1.,  1.,  1., -0.],
       [ 2., -0., -0.,  2.],
       [-0.,  2.,  1., -0.],
       [-1.,  1.,  1.,  2.],
       [-1., -1.,  1., -0.],
       [-1., -0., -0.,  1.],
       [-0., -2.,  1., -0.]])

In [101]:
np.floor(data)

array([[-2.,  0.,  0., -1.],
       [ 1., -1., -1.,  1.],
       [-1.,  1.,  0., -1.],
       [-2.,  0.,  0.,  1.],
       [-2., -2.,  0., -1.],
       [-2., -1., -1.,  0.],
       [-1., -3.,  0., -1.]])

In [102]:
np.rint(data)

array([[-2.,  0.,  1., -1.],
       [ 1., -1., -0.,  1.],
       [-1.,  1.,  0., -0.],
       [-1.,  0.,  1.,  1.],
       [-1., -1.,  0., -1.],
       [-1., -1., -0.,  1.],
       [-0., -2.,  1., -0.]])

In [103]:
np.isnan(data)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [104]:
data

array([[-1.97696942,  0.03951091,  0.72975879, -0.91479572],
       [ 1.11712003, -0.69278979, -0.16454356,  1.11890073],
       [-0.92112628,  1.49994811,  0.09167615, -0.17076331],
       [-1.02878243,  0.16361544,  0.62628984,  1.07207584],
       [-1.36968275, -1.18175284,  0.22646402, -0.87985383],
       [-1.0750434 , -0.79882925, -0.30056976,  0.92361285],
       [-0.08016755, -2.0701819 ,  0.75528139, -0.48997173]])

In [105]:
np.add(data, 5)

array([[3.02303058, 5.03951091, 5.72975879, 4.08520428],
       [6.11712003, 4.30721021, 4.83545644, 6.11890073],
       [4.07887372, 6.49994811, 5.09167615, 4.82923669],
       [3.97121757, 5.16361544, 5.62628984, 6.07207584],
       [3.63031725, 3.81824716, 5.22646402, 4.12014617],
       [3.9249566 , 4.20117075, 4.69943024, 5.92361285],
       [4.91983245, 2.9298181 , 5.75528139, 4.51002827]])

In [108]:
data

array([[-1.97696942,  0.03951091,  0.72975879, -0.91479572],
       [ 1.11712003, -0.69278979, -0.16454356,  1.11890073],
       [-0.92112628,  1.49994811,  0.09167615, -0.17076331],
       [-1.02878243,  0.16361544,  0.62628984,  1.07207584],
       [-1.36968275, -1.18175284,  0.22646402, -0.87985383],
       [-1.0750434 , -0.79882925, -0.30056976,  0.92361285],
       [-0.08016755, -2.0701819 ,  0.75528139, -0.48997173]])

#### np.where
Si se cumple una condición haz una cosa u otra

In [110]:
np.where(data > 0, True, False)

array([[False,  True,  True, False],
       [ True, False, False,  True],
       [False,  True,  True, False],
       [False,  True,  True,  True],
       [False, False,  True, False],
       [False, False, False,  True],
       [False, False,  True, False]])

In [111]:
data

array([[-1.97696942,  0.03951091,  0.72975879, -0.91479572],
       [ 1.11712003, -0.69278979, -0.16454356,  1.11890073],
       [-0.92112628,  1.49994811,  0.09167615, -0.17076331],
       [-1.02878243,  0.16361544,  0.62628984,  1.07207584],
       [-1.36968275, -1.18175284,  0.22646402, -0.87985383],
       [-1.0750434 , -0.79882925, -0.30056976,  0.92361285],
       [-0.08016755, -2.0701819 ,  0.75528139, -0.48997173]])

####  Salvar un array a disco

In [112]:
np.save('data_array', data)


####  Cargar un array de disco

In [114]:
datal = np.load('data_array.npy')

In [115]:
type(datal)

numpy.ndarray

In [116]:
data2

array([[ 0.3       ,  0.07644921, -0.1658253 ,  0.08138635],
       [ 0.36483382, -1.30008441, -1.02978869,  0.26768644],
       [-0.73140415, -1.01661321, -0.20670884, -0.20453093],
       [ 0.5919085 , -1.49374556,  0.39171511, -1.13855594]])

#### Salvar varios arrays

In [118]:
np.savez('save_array', a=data, b=data2)

In [122]:
arch = np.load('save_array.npz')

In [123]:
arch

In [124]:
type(arch)

numpy.lib.npyio.NpzFile

In [128]:
# recuperar el array al que dimos el nombre de a

arch['a']

array([[-1.97696942,  0.03951091,  0.72975879, -0.91479572],
       [ 1.11712003, -0.69278979, -0.16454356,  1.11890073],
       [-0.92112628,  1.49994811,  0.09167615, -0.17076331],
       [-1.02878243,  0.16361544,  0.62628984,  1.07207584],
       [-1.36968275, -1.18175284,  0.22646402, -0.87985383],
       [-1.0750434 , -0.79882925, -0.30056976,  0.92361285],
       [-0.08016755, -2.0701819 ,  0.75528139, -0.48997173]])

In [133]:
np.random.rand(100)

array([0.4897932 , 0.27931502, 0.632973  , 0.63449246, 0.23355499,
       0.93379032, 0.990677  , 0.49067185, 0.4315117 , 0.15816648,
       0.31757578, 0.27436737, 0.18318743, 0.78920315, 0.50011023,
       0.22628308, 0.06898975, 0.53074502, 0.43453589, 0.30981597,
       0.6244999 , 0.70368474, 0.89632579, 0.19557886, 0.24479211,
       0.53787406, 0.82994657, 0.00904823, 0.66833901, 0.41170144,
       0.80133138, 0.926391  , 0.5524936 , 0.62925057, 0.04200116,
       0.84930239, 0.43591458, 0.89020859, 0.65239727, 0.36517081,
       0.65249876, 0.82100389, 0.02273923, 0.68509415, 0.62722073,
       0.72527648, 0.94295899, 0.89124446, 0.40347064, 0.68097924,
       0.57346274, 0.89611101, 0.24954741, 0.44824949, 0.21340271,
       0.93541528, 0.19629624, 0.18866516, 0.91399304, 0.92587311,
       0.74161886, 0.94086418, 0.40963426, 0.57028681, 0.0759244 ,
       0.85897075, 0.89662671, 0.61926679, 0.94741956, 0.83630903,
       0.5988905 , 0.26382526, 0.89063729, 0.28085612, 0.37330

In [135]:
np.random.randint(0, 100, 10)

array([19, 59,  1, 93, 12, 90, 40,  1,  6, 65])

In [136]:
np.random.randn(10)

array([ 1.09649516, -1.26818019, -0.1923157 ,  0.0218038 ,  0.8328638 ,
        0.62721847, -1.15229029, -1.15922459, -0.14758787,  0.53284475])