# Numpy

In [1]:
import numpy as np # por convención, se usa el alias np

In [15]:
np.__version__ #versión de numpy

'1.14.3'

In [16]:
# understanding data types in Python
x = 4
type(x)

int

In [17]:
# tipos de las variables no se declaran explicitamente, son inferidas
x='four' 
type(x)

str

In [19]:
#permite asignar cualquier valor a cualquier variable y cambiar la tipología
x=4
x= 'four'

# Listas

In [31]:
L = list(range(10))

In [32]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
type(L[0])

int

In [34]:
L2 = [str(c) for c in L]

In [35]:
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [36]:
type(L2[0])

str

In [37]:
L3 =  [True, "2", 3.0, 4]

In [38]:
L3

[True, '2', 3.0, 4]

In [39]:
[type(c) for c in L3]

[bool, str, float, int]

Cada item de la lista es un objeto, que lleva implícita su
cabecera de objeto : PyObject_HEAD (reference, type, size, value).

Si todos los items son del mismo tipo, mucha de la información de cabecera es redundante lo que supone un coste adicional en memoria e ineficiencia en el tratamiento



# Arrays

In [40]:
import array

In [41]:
L= list(range(10))

In [43]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
A = array.array('i', L)

In [45]:
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
type(L)

list

In [76]:
type(A)

array.array

# Numpy Arrays

Los arrays de numpy contienen valores de un único tipo

In [77]:
import numpy as np

In [78]:
# integer array
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [79]:
# float array
np.array([1.3,4.1,2.0,5.0,-3.9])

array([ 1.3,  4.1,  2. ,  5. , -3.9])

In [80]:
# np is constrained to array that all contain the same type. If types do no match
# Numpy will upcast if possible 

np.array([13,4,2,5,3.5])

array([13. ,  4. ,  2. ,  5. ,  3.5])

In [2]:
A2 = np.array(["hola","adios","barco"])

In [3]:
A2

array(['hola', 'adios', 'barco'], dtype='<U5')

In [4]:
A2.dtype

dtype('<U5')

In [128]:
A3 = np.array([range(i, i+3) for i in [2,3,4]])

In [129]:
A3

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [130]:
type(A3)

numpy.ndarray

In [85]:
[range(i, i+3) for i in [2,3,4]]

[range(2, 5), range(3, 6), range(4, 7)]

In [103]:
[c for c in range(5)]

[0, 1, 2, 3, 4]

In [105]:
[[c, c+1] for c in range(4)]

[[0, 1], [1, 2], [2, 3], [3, 4]]

In [112]:
# range is an object, not a list object
rn = range(10)

In [113]:
type(rn)

range

In [116]:
# to convert range to a list
rnl = list(rn)

In [117]:
rnl

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [120]:
# convert array to string
A4 = np.array(["hola",1,2.5])

In [121]:
A4

array(['hola', '1', '2.5'], dtype='<U4')

In [122]:
A5 = np.array([["Hola","Adios"], [0, 1, 2], [3.4,5.0, 6.7]])

In [123]:
A5

array([list(['Hola', 'Adios']), list([0, 1, 2]), list([3.4, 5.0, 6.7])],
      dtype=object)

In [131]:
type(A5)

numpy.ndarray

In [127]:
A6 = np.array([[2,7], [0, 1, 2], [4,5,8]])

In [125]:
A6

array([list([2, 7]), list([0, 1, 2]), list([4, 5, 8])], dtype=object)

In [132]:
type(A6)

numpy.ndarray

## Creando Arrays

Métodos para crear arrays

* zeros.- crea un array con ceros  -> np.zeros(10, dtype=int)
* ones.- crea un array con unos    -> np.ones((3,5), dtype=float)
* full.- crea un array con un valor concreto -> np.full((3,5), 3.14)
* arange.-  crea un array unidimensional   -> np.arange(start, end, step)
* linspace.- crea un array unidimensional con mín, máx y elementos -> np.linspace(m,M,e)
* random.random.- crea un array random distribución uniforme -> np.random.random((3,3))
* random.normal.- crea un array random distribución normal 
   -> np.random.normal(mean, std, (3,3))
* random.randint.- crea  un array random de enteros en un intervalo 
   -> np.random.randint(start, end, (3,3))
* eye.- crea una matriz identidad -> np.eye(3)
* empty.- crea un array no inicializado -> np.empty(3)



In [47]:
np.ones((3,4), dtype='int8')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [136]:
np.eye(5) #matriz identidad

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [137]:
np.zeros(10) #array de 10 valores rellenos con 0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [138]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [140]:
np.ones((3,5)) # crea un array de 3x5 relleno con 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [141]:
np.full((3,5), 3.14) # crea un array de 3x5 relleno con 3.14

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [142]:
np.arange(0,20,2) #matriz con un range ()

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [143]:
np.linspace(0, 1, 10) #matriz de 10 valores entre 0 y 1, equidistantes

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [144]:
np.random.random((3,3))

array([[0.66502876, 0.39023562, 0.38959976],
       [0.39018608, 0.15762843, 0.20891702],
       [0.58805563, 0.12603266, 0.37604919]])

In [146]:
np.random.normal(0,1,(3,3)) #array de 3x3 con números aleatorios dist normal m 0 y sd 1

array([[-0.39485613,  0.52942476, -0.83872812],
       [-0.00674758,  0.84392314,  1.8243008 ],
       [ 0.12550983, -0.73296348,  0.52469965]])

In [148]:
np.random.randint(0,10, (4,4)) # array de 4x4 con random int entre 0 y 10


array([[2, 5, 7, 8],
       [1, 1, 5, 3],
       [7, 2, 0, 1],
       [6, 8, 6, 1]])

In [151]:
npe = np.empty(3) # array no inicializado

In [152]:
npe

array([0.00000000e+000, 1.00000000e+000, 7.69165785e+218])

In [153]:
type(npe)

numpy.ndarray

In [155]:
npe.fill(0)

In [156]:

npe

array([0., 0., 0.])

## The Basics of NumPy Arrays

Manipulación de datos en Python es sinónimo de manipulación de arrays con Numpy. Pandas está construido alrededor del array de NumPy.

### NumPy array atributes


* ndim.- número de dimensiones 
* shape.- tamaño de cada una de las dimensiones
* size.- total de elementos 
* itemsize.- tamaño de cada item en bytes
* nbytes.- tamaño total en bytes

In [1]:
import numpy as np

In [3]:
np.random.seed(0)

x1 = np.random.randint(10, size=6) # una dimensión
x2 = np.random.randint(10, size=(3, 4)) # dos dimensiones
x3 = np.random.randint(10, size=(3, 4, 5)) #tres dimensiones

In [4]:
print(x1.ndim) # número de dimensiones del array
print(x2.ndim)
print(x3.ndim)


1
2
3


In [5]:
print(x1.shape) # tamaño de cada dimensión
print(x2.shape)
print(x3.shape)

(6,)
(3, 4)
(3, 4, 5)


In [6]:
print(x1.size) # tamaño total del array (número de elementos)
print(x2.size)
print(x3.size)

6
12
60


In [7]:
print(x1.dtype) # tipo de dato del array (es el mismo para todos por ser un array numpy)
print(x2.dtype)
print(x3.dtype)

int64
int64
int64


In [8]:
type(x1)

numpy.ndarray

In [9]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [10]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [11]:
print(x1.itemsize) # tamaño de cada elemento (en bytes)
print(x2.itemsize)
print(x3.itemsize)

8
8
8


In [12]:
print(x1.nbytes) # tamaño total en bytes
print(x2.nbytes)
print(x3.nbytes)

48
96
480


### Array Indexing

Acceso a los elementos del array, es bastante similar al acceso en el standar de Python.
El índice empieza en 0

#### Acceso a los elementos

* Acceso a un elemento concreto en un array unidimensional x[d1]
* Acceso a un elemento concreto en un array multidimensional x[d1,d2,...]

#### Modificación de los elementos

* Modificación del valor de un elemento x[d1] = new value

Recordar que todos los elementos del array tienen el mismo valor, por lo que si intentamos asignar un valor de otro tipo, este será modificado para adaptarlo a la tipología y si no lo consigue dará un error

In [13]:
x1

array([5, 0, 3, 3, 7, 9])

In [14]:
x1[1] #acceso al segundo elemento de la lista

0

In [15]:
x1[-1] #acceso al último elemento de la lista

9

In [16]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [17]:
x2[2,2] # acceso a la fila 3, elemento 3 (separaciones entre comas)

7

In [18]:
x1

array([5, 0, 3, 3, 7, 9])

In [19]:
x1[0] = 3 #modificar el valor del primer elemento

In [20]:
x1

array([3, 0, 3, 3, 7, 9])

In [21]:
x1[0] = 'Hola' # error al no poder convertir hola en un entero

ValueError: invalid literal for int() with base 10: 'Hola'

### Array Slicing - Accessing Subarrays

Acceso a varios elementos del array utilizando la notación "slice" con los dos puntos (:)
Sintaxis:

x[start:stop:step]


Si no se especifica alguno de los indices, tomaran por defecto:

* start = 0
* stop = size of dimension
* step = 1

El valor de stop no se incluye en la selección



#### Arrays unidimensionales

In [22]:
x4 = np.arange(10)

In [23]:
x4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x4[:4] # 4 primeros elementos 

array([0, 1, 2, 3])

In [25]:
x4[6:8] #elemento 6 y 7

array([6, 7])

In [26]:
x4[7:] #elementos desde el 7 hasta el final

array([7, 8, 9])

In [27]:
x4[::2] # elementos desde el principio al final, de dos en dos

array([0, 2, 4, 6, 8])

In [28]:
# si los pasos son en negativo, el inicio y stop se voltean y devuelve 
#el resultado en orden inverso
x4[::-1] 


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### Arrays multidimensionales


Funcionan del mismo modo que los arrays unidimensionales

In [29]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [30]:
x2[1:,2:] # dos filas y dos columnas

array([[8, 8],
       [7, 7]])

In [31]:
x2[:, ::2] # todas las filas, las columnas de dos en dos

array([[3, 2],
       [7, 8],
       [1, 7]])

In [32]:
x2[::-1, ::-1] #invierte el array

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

### Accediendo a filas y columnas del array

In [33]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [35]:
x2[:,0] #primera columna

array([3, 7, 1])

In [36]:
x2[0,:] #primera fila

array([3, 5, 2, 4])

In [37]:
x2[0] #primera fila

array([3, 5, 2, 4])

### Subarrays no son copias del array, son vistas (punteros) 
### .copy()

Si se modifica un valor del subarray este afecta al array. A diferencia de las listas en Python, donde al hace Slicing se generan copias de las listas. 

Para generar una copia, se usa el metodo copy()


In [54]:
x6 = x2[:2,:2] # creamos una variable con un subarray

In [55]:
x6

array([[8, 5],
       [7, 6]])

In [56]:
x6[0,0] = 8

In [57]:
x6 # al actualizar el subarray

array([[8, 5],
       [7, 6]])

In [58]:
x2 # se actualiza el array; sería un puntero sobre el array

array([[8, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [59]:
x6_copy = x2[:2,:2].copy() # creamos una copia con un subarray

In [60]:
x6_copy[0,0] = 9

In [61]:
x6_copy # se modifica el valor de la copia

array([[9, 5],
       [7, 6]])

In [62]:
x2 # pero el valor del array original no se modifica

array([[8, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

### Reshaping of Arrays
### .reshape()

Cogemos un determinado array y cambiamos la estructura de este

In [21]:
grid = np.arange(1, 10).reshape((3,3)) # el tamaño debe machear con la nueva definición

In [22]:
grid_ = np.arange(1, 10).reshape((3,4)) # el tamaño debe machear con la nueva definición

ValueError: cannot reshape array of size 9 into shape (3,4)

In [23]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
grid.shape

(3, 3)

In [25]:
grid2 = np.arange(1,4)

In [26]:
grid2

array([1, 2, 3])

In [27]:
grid2[np.newaxis,:]  # similar a grid2.reshape(1,3)

array([[1, 2, 3]])

In [29]:
grid2[:, np.newaxis] # similar a grid2.reshape(3,1)

array([[1],
       [2],
       [3]])

In [20]:
grid2[np.newaxis,:]

array([[1, 2, 3]])

### Concatenación de Arrays

* np.concatenate() .- concatena arrays
* np.vstack() .- concatena arrays en vertical
* np.hstack() .- concatena arrays en horizontal
* np.dstack() .- concatena arrays a través del tercer eje

In [64]:
x = np.arange(1,4)
y = np.arange(4,8)


In [65]:
x

array([1, 2, 3])

In [66]:
y

array([4, 5, 6, 7])

In [67]:
np.concatenate([x,y]) # anida dos arrays unidimensionales

array([1, 2, 3, 4, 5, 6, 7])

In [68]:
grid4 = np.array ([[1,2,3],
                  [4,5,6]])

In [69]:
grid4

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
np.concatenate([grid4, grid4]) # concatena en vertical

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [71]:
np.concatenate([grid4, grid4], axis=1) # concatena en horizontal

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [72]:
np.vstack([x, grid4]) # concatena en vertical


array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [73]:
grid4

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
grid5 = np.array([[7],
                  [8]])

In [75]:
grid5

array([[7],
       [8]])

In [76]:
grid5.ndim

2

In [77]:
grid5.shape

(2, 1)

In [78]:
grid5.size

2

In [79]:
np.hstack([grid4, grid5]) # concatena en horizontal

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

### Cortando Arrays

* np.split() .- cortando arrays
* np.vsplit() .- cortando arrays en vertical
* np.hsplit() .- cortando arrays en horizontal
* np.dsplit() .- cortando arrays a través del tercer eje

In [81]:
x = np.arange(10)

In [82]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
xs1, xs2, xs3 = np.split(x, [3,5]) # divide el array x en tres 0..3..5..9

In [90]:
xs1

array([0, 1, 2])

In [91]:
xs2

array([3, 4])

In [92]:
xs3

array([5, 6, 7, 8, 9])

In [94]:
grid6=np.arange(16).reshape((4,4))

In [95]:
grid6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
upper_, lower_ = np.vsplit(grid6,[2]) #dividir verticalmente en 2


In [98]:
upper_

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [99]:
lower_

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [103]:
left_, right_ = np.hsplit(grid6,[2]) #dividir horizontalmente en 2

In [104]:
left_

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [105]:
right_

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])